import type { Promotion } from "@/types/database";

// Sample promotions matching StoreHub's 5 types

export const SAMPLE_PROMOTIONS: Promotion[] = [
  {
    // Auto-apply: Buy 2 coffees, get 1 free (cheapest free)
    id: "promo1",
    brand_id: "b1",
    name: "Buy 2 Get 1 Free Coffee",
    promo_code: null,
    discount_type: "buy_x_get_y",
    discount_value: null,
    combo_price: null,
    override_price: null,
    buy_quantity: 2,
    free_quantity: 1,
    apply_to: "category",
    apply_min_order: null,
    apply_categories: ["coffee"],
    apply_tags: [],
    apply_product_ids: [],
    apply_min_qty: null,
    apply_max_qty: null,
    require_purchase: false,
    require_categories: [],
    require_tags: [],
    require_product_ids: [],
    require_min_qty: null,
    customer_eligibility: "everyone",
    eligible_customer_tags: [],
    eligible_membership_tiers: [],
    total_usage_limit: null,
    per_customer_limit: null,
    current_usage_count: 0,
    allow_repeat: false,
    channels: ["pos"],
    branch_ids: null,
    is_enabled: true,
    start_date: null,
    end_date: null,
    created_at: "",
    updated_at: "",
  },
  {
    // Auto-apply: Breakfast combo (Egg Croissant + any Coffee = RM 22)
    id: "promo2",
    brand_id: "b1",
    name: "Breakfast Combo",
    promo_code: null,
    discount_type: "combo_bundle",
    discount_value: null,
    combo_price: 2200,
    override_price: null,
    buy_quantity: null,
    free_quantity: null,
    apply_to: "specific_products",
    apply_min_order: null,
    apply_categories: [],
    apply_tags: [],
    apply_product_ids: ["p2", "p11"], // Hot Latte + Egg Croissant
    apply_min_qty: 2,
    apply_max_qty: null,
    require_purchase: false,
    require_categories: [],
    require_tags: [],
    require_product_ids: [],
    require_min_qty: null,
    customer_eligibility: "everyone",
    eligible_customer_tags: [],
    eligible_membership_tiers: [],
    total_usage_limit: null,
    per_customer_limit: null,
    current_usage_count: 0,
    allow_repeat: false,
    channels: ["pos"],
    branch_ids: null,
    is_enabled: true,
    start_date: null,
    end_date: null,
    created_at: "",
    updated_at: "",
  },
  {
    // Manual: 10% off orders over RM 30
    id: "promo3",
    brand_id: "b1",
    name: "10% Off Over RM30",
    promo_code: "SAVE10",
    discount_type: "percentage_off",
    discount_value: 1000, // 10% in basis points
    combo_price: null,
    override_price: null,
    buy_quantity: null,
    free_quantity: null,
    apply_to: "orders_over",
    apply_min_order: 3000, // RM 30 in sen
    apply_categories: [],
    apply_tags: [],
    apply_product_ids: [],
    apply_min_qty: null,
    apply_max_qty: null,
    require_purchase: false,
    require_categories: [],
    require_tags: [],
    require_product_ids: [],
    require_min_qty: null,
    customer_eligibility: "everyone",
    eligible_customer_tags: [],
    eligible_membership_tiers: [],
    total_usage_limit: null,
    per_customer_limit: null,
    current_usage_count: 0,
    allow_repeat: false,
    channels: ["pos", "online", "qr"],
    branch_ids: null,
    is_enabled: true,
    start_date: null,
    end_date: null,
    created_at: "",
    updated_at: "",
  },
  {
    // Manual: RM 5 off any order
    id: "promo4",
    brand_id: "b1",
    name: "RM5 Off Welcome",
    promo_code: "WELCOME5",
    discount_type: "amount_off",
    discount_value: 500, // RM 5 in sen
    combo_price: null,
    override_price: null,
    buy_quantity: null,
    free_quantity: null,
    apply_to: "all_orders",
    apply_min_order: null,
    apply_categories: [],
    apply_tags: [],
    apply_product_ids: [],
    apply_min_qty: null,
    apply_max_qty: null,
    require_purchase: false,
    require_categories: [],
    require_tags: [],
    require_product_ids: [],
    require_min_qty: null,
    customer_eligibility: "everyone",
    eligible_customer_tags: [],
    eligible_membership_tiers: [],
    total_usage_limit: 100,
    per_customer_limit: 1,
    current_usage_count: 0,
    allow_repeat: false,
    channels: ["pos", "online", "qr"],
    branch_ids: null,
    is_enabled: true,
    start_date: null,
    end_date: null,
    created_at: "",
    updated_at: "",
  },
];
